### ISSUE TITLE
Two-way binding causes System.Windows.Data Error: 8

### ISSUE THREAD

**Issue by JohnStov** [Prolucid/Elmish.WPF#15] opened 2017-07-07 11:54 UTC
I'm just playing around with this for now. Generally works very nicely.

I have a slider control with a TwoWay binding to the Value property.

Every time I move the slider I get this error message: 
    _System.Windows.Data Error: 8 : Cannot save value from target back to source._

Is there a workaround? Is it a bug?

It looks like the problem is that the value change creates a message which updates the model, and then the model change triggers a view update with the value that was just supplied.

I can provide a repro if needed.

**Comment by 2sComplement** [comment] 2017-07-07 12:03
This is a duplicate of #10.  The ViewModel is trying to prevent an immediate get after the view sets the binding source, and the prevention results in the view thinking that the value was not set. It is a minor bug since these exceptions may have an effect on performance, but shouldn't affect your values or functionality.

**Closed by 2sComplement** 2017-07-07 12:03 UTC
